---
- name: static provision
  hosts: 10.10.0.102
  
  tasks:
    - name: install pkg
      become: yes
      apt:      
        pkg: apache2      
        state: present        
        
    - name: change permission
      file:
        path: /var/www/html
        mode: '755'

    - name: copy index.html
      become: yes
      copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html

- name: dynamic provision
  hosts: 10.10.0.103

  tasks:
    - name: install pkg
      become: yes
      apt:      
        pkg:
          - apache2
          - php        
        state: present 

    - name: copy index.php
      become: yes
      copy:
        src: /vagrant/index.php
        dest: /var/www/html/index.php 

    - name: remove index.html
      become: yes
      file:
        path: /var/www/html/index.html
        state: absent

- name: reverse_proxy provision
  hosts: 10.10.0.104

  tasks:
    - name: install nginx
      become: yes
      apt:      
        pkg: nginx      
        state: present

    - name: config nginx
      become: yes
      blockinfile:
        path: /etc/nginx/sites-available/default
        create: true
        block: |
          server {
              listen 80;
              listen [::]:8080;
              server_name 192.168.33.11;
              location /index.html {
                  proxy_pass http://192.168.33.12:80;
              }
              
              location /index.php {
                  proxy_pass http://192.168.33.13:80;
              }
              
          }
    
    - name: add to enabled
      become: yes
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        owner: root
        group: root
        force: yes 
    
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
      



         