---
- name: static provision
  hosts: 10.10.0.102
  
  tasks:
    - name: install pkg
      become: yes
      apt:      
        pkg: apache2      
        state: present        
        
    - name: change permission
      file:
        path: /var/www/html
        mode: '755'

    - name: copy index.html
      become: yes
      copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html

- name: dynamic provision
  hosts: 10.10.0.103

  tasks:
    - name: install pkg
      become: yes
      apt:      
        pkg:
          - apache2
          - php        
        state: present 

    - name: copy index.php
      become: yes
      copy:
        src: /vagrant/index.php
        dest: /var/www/html/index.php 

    - name: remove index.html
      become: yes
      file:
        path: /var/www/html/index.html
        state: absent

- name: reverse_proxy provision
  hosts: 10.10.0.104

  tasks:
    - name: install nginx
      become: yes
      apt:      
        pkg: nginx      
        state: present

    - name: config nginx
      become: yes
      blockinfile:
        destfile: /etc/nginx/sites-available/default
        create: true
        block: |
          server {
            {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.html index.htm index.nginx-debian.html;
              server_name proxy;
              proxy_set_header X-Scheme http;
              proxy_set_header X-Forwarded-Proto http;
              proxy_set_header Host $http_host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Real-PORT $remote_port;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_buffering on;
              proxy_buffer_size 8k;
              proxy_buffers 8 8k;
              location / {
                try_files $uri $uri/ =404;
        
             location /index.html {
                proxy_pass http://10.10.0.102/index.html;
              }
        
        
              location /index.php {
                proxy_pass http://10.10.0.103/index.php;
              }
            }
    
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
      



         