---
- name: Master provision
  hosts: all
  
  tasks:
    - name: install pkg
      become: yes
      apt:      
        pkg:
          - apache2
          - php        
        state: present        
        
    - name: create folder php
      become: yes
      file:
        path: /var/www/php
        state: directory
        mode: '755'

    - name: change permissions
      file:
        path: /var/www/html
        mode: '755'

    - name: change permissions apache2
      become: yes
      file:
        path: /etc/apache2
        mode: '755'

    - name: replace ports.conf
      become: yes
      copy:
        src: /vagrant/ports.conf
        dest: /etc/apache2/ports.conf

    - name: copy php config
      become: yes
      copy:
        src: /vagrant/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf

    - name: copy index.html
      become: yes
      copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html

    - name: copy index.php
      become: yes
      copy:
        src: /vagrant/index.php
        dest: /var/www/php/index.php
        
    - name: restart apache2
      become: yes
      service:
        name: apache2
        state: restarted
         