Vagrant.configure("2") do |config| 
  config.vm.box = "generic/debian9"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"
  end

  config.vm.define "master", primary: true do |master| #машина, с которой запускаем playbook, так как у меня Windows
    master.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y ansible
      apt install -y sshpass
      chmod 755 /etc/ansible/
      cp /vagrant/index.php /etc/ansible/    
  SHELL
  end

  config.vm.define "slave", primary: true do |slave|
      slave.vm.network "private_network", ip: "10.10.0.101"
      slave.vm.network "forwarded_port", guest: 80, host: 8080
      slave.vm.network "forwarded_port", guest: 81, host: 8081
  end

end