Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian9"
    config.vm.network "private_network", ip: "10.10.0.100"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    config.vm.synced_folder ".", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "homework01_debian"        
        vb.memory = "512"
        
    end

    config.vm.provision "shell", inline: <<-SETUP
        apt update
        apt install -y apache2
        apt install -y php
        sudo mkdir /var/www/php/
        sudo cp /vagrant/index.php /var/www/php/index.php
        sudo cp /vagrant/index.html /var/www/html/index.html
        sudo cp /vagrant/ports.conf /etc/apache2/ports.conf 
        sudo cp /vagrant//000-default.conf /etc/apache2/sites-available/000-default.conf
    SETUP

        #config.vm.provision "file", source: "./index.php", destination: "/var/www/php/"
        #config.vm.provision "file", source: "./index.html", destination: "/var/www/html/"
        #config.vm.provision "file", source: "./ports.conf", destination: "/etc/apache2/"
        #config.vm.provision "file", source: "./000-default.conf", destination: "/etc/apache2/sites-available/"

        config.vm.provision "shell", inline: "sudo systemctl restart apache2"
end